name: rideupt_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  http: ^1.2.1
  shared_preferences: ^2.3.2
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  intl: ^0.18.1
  geocoding: ^4.0.0
  ntp: ^2.0.0
  flutter_local_notifications: ^17.1.2
  firebase_messaging: ^14.9.4
  socket_io_client: ^2.0.3+1
  firebase_core: ^2.32.0
  google_sign_in: ^6.2.1
  firebase_auth: ^4.20.0
  flutter_secure_storage: ^9.2.4
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
